name: CamikePress
favicon: null
layout_spectrum: 0.710644414415583
typography_spectrum: 0.899722792673856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.13336228532716632
  lightness: 0.7610814389772713
  saturation: 0.27088358672335744
  rhythmicContrast: 0.06802466092631221
purpose: []
